### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by robatgithub** [googlesamples/android-play-location#1]
Hi.
I got null at: 

    public void onConnected(Bundle connectionHint) {
        mLastLocation = LocationServices.FusedLocationApi.getLastLocation(mGoogleApiClient);

best regards
Rob

**Comment by shailen** [comment]
@robatgithub Using getLastLocation() can return null in rare cases. Did you have location enabled in your device's settings?

**Comment by shailen** [comment]
Closing this, since a null is not necessarily indicative of an error.
