### ISSUE TITLE
Can I use this in a production app

### ISSUE THREAD

**Issue by emayoung** [googlesamples/android-play-location#107]
Warning: Please continue using the FusedLocationProviderApi class and don't migrate to the FusedLocationProviderClient class until Google Play services version 12.0.0 is available, which is expected to ship in early 2018. Using the FusedLocationProviderClient before version 12.0.0 causes the client app to crash when Google Play services is updated on the device. We apologize for any inconvenience this may have caused

This warning is included here https://developer.android.com/training/location/retrieve-current.html#setup. Can I continue to use this in a production app or heed to this warning? 

The app runs well though

**Comment by mohitagrawal** [comment]
I think you should heed this warning. You might see crashes happen when Google Play Services is updated on the device. Though that shouldn't happen very frequency but why take the chance?

**Comment by samtstern** [comment]
@emayoung as @mohitagrawal said this issue will cause some crashes when Google Play services is updated on the devices, which happens infrequently (every few weeks) but probably not infrequently enough to totally ignore.

The good news is we have a fix coming for this issue sooner than expected, look out for version `11.6.0` or higher soon which should fix the issue.

**Comment by Eqbalazar** [comment]
Hi **emayoung**

I can not find warning message on [ https://developer.android.com/training/location/retrieve-current.html#setup.](url)
That means we can use it in production  ???

**Comment by samtstern** [comment]
@Eqbalazar thanks for noticing.  We got the fix out sooner than expected, so no warning is necessary anymore.  You can feel confident using this API in production.

cc: @emayoung @mohitagrawal

**Comment by Eqbalazar** [comment]
It seems when phone is in Airplane Mode it couldn't get current location even Location is Enabled .
