### ISSUE TITLE
Sample is not showing any notification

### ISSUE THREAD

**Issue by MotassemJa** [googlesamples/android-play-location#111]
After clicking on the "Add Geofences" button and changing the location of the emulator to match exactly the locations in the Constants class, but no notification is triggered. Tested on API 24, 25, and 26!

Hope to get a feedback since I need to use the API in my project for showing a notification when user is inside a geofence.

**Comment by Fraid** [comment]
I was just facing the same issue on a real device, I restarted the phone and everything was working as expected. Maybe try on a real device first?

**Comment by MotassemJa** [comment]
I tested on actual device as well but didn't work. I only get an exit event when I click on remove then add directly.

**Comment by juffreycalauod** [comment]
i did not receive any notifications any solutions please

**Comment by frankgh** [comment]
Hi, 

If you are using Android O, notifications will not work. I have provided a Pull Request that fixes the notification issues. Please take a look at the code here:

https://github.com/googlesamples/android-play-location/pull/115

Android O introduces notification channels, for more information visit: https://developer.android.com/guide/topics/ui/notifiers/notifications.html#ManageChannels

**Comment by MotassemJa** [comment]
Hi @frankgh ,

Thank you for your reply. But I have already read about notification channels and implemented it but no results. Doe Geofence API even work when the app is killed??

**Comment by frankgh** [comment]
Hi @MotassemJa ,

Yes. The Geofence API works when the app is killed. But the geofences have an expiration duration. Here are a few things you can look into:

- While building the Geofences `Geofence.Builder()` make sure you set the expiration duration to the value appropriate for your application:
   ```
   mGeofenceList.add(new Geofence.Builder()
                    // Set the request ID of the geofence. This is a string to identify this
                    // geofence.
                    .setRequestId(entry.getKey())

                    // Set the circular region of this geofence.
                    .setCircularRegion(
                            entry.getValue().latitude,
                            entry.getValue().longitude,
                            Constants.GEOFENCE_RADIUS_IN_METERS
                    )

                    // Set the expiration duration of the geofence. This geofence gets automatically
                    // removed after this period of time.
                    .setExpirationDuration(Geofence.NEVER_EXPIRE)

                    // Set the transition types of interest. Alerts are only generated for these
                    // transition. We track entry and exit transitions in this sample.
                    .setTransitionTypes(Geofence.GEOFENCE_TRANSITION_ENTER |
                            Geofence.GEOFENCE_TRANSITION_EXIT)

                    // Create the geofence.
                    .build());
   ```
- You need to re-register geofences for the following cases
   1. The device is rebooted. The app should listen for the device's boot complete action, and then re- register the geofences required.
   2. The app is uninstalled and re-installed.
   3. The app's data is cleared.
   4. Google Play services data is cleared.
   5. The app has received a GEOFENCE_NOT_AVAILABLE alert. This typically happens after NLP (Android's Network Location Provider) is disabled.

Hope this helps,

**Comment by MotassemJa** [comment]
I have no idea why it is not working with me even when I set the expiration to NEVER_EXPIRE
I'm running the app, adding the geofence, closing the app and removing it from the recent apps list, and then navigating to the geofence. But no notification is showing, even no log entries.

**Comment by MotassemJa** [comment]
@frankgh I noticed that even if the Activity is finished and another activity is shown, the app wont show any notification. Can that be because of the Context I'm passing to the location service? Should the geofencing code be in the Application class instead of an activity?

**Comment by frankgh** [comment]
@MotassemJa I believe you could be facing some of the issues described in this answer:
https://stackoverflow.com/questions/46450225/geofence-events-not-always-called/46538931#46538931
Let me know if that helps

**Comment by MotassemJa** [comment]
@frankgh Unfortunately didn't help.
The geofencing API should get the updates sooner than Fused Location Provider or the LocationManager as described here https://developer.android.com/about/versions/oreo/background-location-limits.html#apis
I even tried setting an intent filter with a very high priority, but it didn't work as well.

**Comment by frankgh** [comment]
@MotassemJa I'm busy until next week, but I will put something together that you can try to debug your problem.

**Comment by frankgh** [comment]
@MotassemJa  I have modified the code so that the notifications are displayed even when the app is killed. However, you still need to handle the case where the phone has been rebooted, the app's data is cleared, and Google Play services data is cleared.

The code can be found here:
https://github.com/frankgh/android-play-location/tree/background-service

**Comment by MotassemJa** [comment]
@frankgh Thank you for your efforts. This time it is not even showing any notification even when the app is opened. I ran the app on an emulator with API 26 and navigated to the coordinates in the Constants class but still nothing is shown.
I added some logging:
```
01-05 13:14:18.631 6348-6348/com.google.android.gms.location.sample.geofencing D/MainActivity: getGeofencePendingIntent
01-05 13:14:18.631 6348-6348/com.google.android.gms.location.sample.geofencing D/MainActivity: PendingIntent is not null
01-05 13:14:18.656 6348-6348/com.google.android.gms.location.sample.geofencing D/MainActivity: onTaskCompleted
```

**Comment by frankgh** [comment]
@MotassemJa I haven't tried it on the emulator, I will try later today. Have you tested it on a phone?

**Comment by MotassemJa** [comment]
@frankgh It worked on a phone. Thank you very much for your support

**Comment by swatantra109** [comment]
Working on Mi device well but in some samsung device it works one time after user is not receiving exit or enter transition not able to know why?
