### ISSUE TITLE
Is possible to use LocationSettings and Geofencing?

### ISSUE THREAD

**Issue by geolyth** [googlesamples/android-play-location#12]
I'm trying to do this since 7 days with no results...

The problem is ResultCallback, for geofencing I need ResultCallback<Status> while for LocationSettings I need ResultCallback<LocationSettingsResult>, is there a way to do this?

I appreciate some tips...

Thanks for your support :)

**Comment by shailen** [comment]
In that case, you need to disambiguate the two ResultCallback objects. I would say the simplest way would be to *not* have MainActivity implement ResultCallback, but simply define two callbacks, one of Geofencing, and one for LocationSettings. 

I think it might be worthwhile to modify the GeoFencing sample to use the LocationSettings dialog.
