### ISSUE TITLE
Geofence issue

### ISSUE THREAD

**Issue by smartandroidhub** [googlesamples/android-play-location#13]
Sometime geofence does not provide result after connection established.
Specially when we call action from service.

**Comment by geolyth** [comment]
In what cases? I have tested for two weeks and I hadn't trouble with geofence in service...

**Comment by smartandroidhub** [comment]
Thanks @geolyth 

Now it is working on my end.:)

**Comment by shailen** [comment]
I am glad it is working. Sometimes Geofences can be a little sluggish in triggering. If you find that to be the case for you, please open another issue describing the problem. Closing this one.
