### ISSUE TITLE
Error when cloning project

### ISSUE THREAD

**Issue by jfpradanativapps** [googlesamples/android-play-location#134]
It seems that the current setting.gradle found in master, is missing a comma. 

`include ':ActivityRecognition:app', ':BasicLocationSample:java:app', ':BasicLocationSample:kotlin:app', ':Geofencing:app', ':LocationAddress:java:app', ':LocationAddress:kotlin:app' ':LocationUpdates:app', ':LocationUpdatesForegroundService:app', ':LocationUpdatesPendingIntent:app'`

between `':LocationAddress:kotlin:app'` and `':LocationUpdates:app'`

**Comment by indraAsLesmana** [comment]
thanks.., 
this is the answer to error "Gradle startup error file setting: blah blah..."

**Comment by dturner** [comment]
Thanks for reporting this. Should be fixed now, please re-open if not.
