### ISSUE TITLE
connecting to google play services

### ISSUE THREAD

**Issue by maryjaho** [googlesamples/android-play-location#14]
I try to connect to google play services using the code of this sample.
But it does n`t connect and return connection result code 8(Internal error occurred.retrying should resolve the problem) and code 2(The installed version of Google Play services is out of date.
 The calling activity should pass this error code to getErrorDialog(int, Activity, int) to get a localized error dialog that will resolve the error when shown.).
I cant understand error code 8. and I installed the latest version of google play services but i still receive error code 2.
Can you help me to resolve this problem and connect to google play services?

**Comment by shailen** [comment]
Can you tell me what version of Play Services you are running?

**Comment by adammfrank** [comment]
I also have this problem with Google Play services 26.0.0

**Comment by dturner** [comment]
Closing as obsolete. Please re-open with the Play Services version and any error messages if you still have a problem connecting.
