### ISSUE TITLE
LocationUpdatesPendingIntent app CLOSED

### ISSUE THREAD

**Issue by jQrgen** [googlesamples/android-play-location#140]
Hello

1. Is the LocationUpdatesPendingIntent sample supposed to fetch locations and display a notification when the app is completely closed? 
2. Is the LocationUpdatesPendingIntent sample supposed to fetch locations and display a notification after re-starting the device?

Thanks

**Comment by deckameron** [comment]
Hi @jQrgen,

Did you try adding this to your manifest?

```xml
<receiver android:name=".GeofenceBroadcastReceiver"
        android:enabled="true"
        android:exported="true">
        <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
        </intent-filter>
</receiver>
```

**Comment by jQrgen** [comment]
Yeah thanks i got it working using a BOOT_COMPLETED receiver.

**Comment by bhavin-chauhan** [comment]
@jQrgen  You've mentioned "Is the LocationUpdatesPendingIntent sample supposed to fetch locations and display a notification when the app is completely closed? ANS : Yes" I've test app in detail but in my case when I close app notification is no longer available.
Build SKD : 29
Phone OS : Android 9 Pie 
Phone Model : POCO F1
There is battery saver mode inbuilt in my phone I've off that and allow full access so background process will work but It is working proper. Can you please guide me what I missed?

**Comment by jQrgen** [comment]
I'm not sure, maybe you need to read up on the API for legacy Android location without fusedLocation? 

Maybe the legacy method does not handle background threads by itself?
