### ISSUE TITLE
expecting EOF found , error

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-play-location#144]
![screen shot 2018-04-11 at 6 45 59 pm](https://user-images.githubusercontent.com/36618485/38618969-b1749064-3db8-11e8-8558-2356b7f7fcd2.png)

when I remove single quote with other manually typed single quote, error changes to:
cannot invoke method LocationUpdates:app()

Please help.

**Comment by mehtadarshak** [comment]
![screen shot 2018-04-11 at 6 58 47 pm](https://user-images.githubusercontent.com/36618485/38619736-7106dbac-3dba-11e8-8d1c-033419c0b733.png)

**Comment by nance2uiuc** [comment]
I also have this problem.

**Comment by nance2uiuc** [comment]
looks like there is a missing    ,   after ':LocationAddress:kotlin:app'. Instert it and the error disappears. but another error appears`. Could not find method implementation() for arguments [com.android.support:appcompat-v7:27.0.2]`

**Comment by behelit** [comment]
Why don't they accept the pull requests or assign someone the permission to?

**Comment by ijkmoises** [comment]
I leave only the app that interests me in the include ': LocationUpdatesForegroundService: app' .

Also update some dependencies in the application build.gradle .

This worked for me.

**Comment by pcegarra** [comment]
same error, first the comma in settings.gradle and now, com.android.support:appcompat-v7:27.0.2

**Comment by dturner** [comment]
Thanks for reporting this. Should be fixed now, please re-open if not.
