### ISSUE TITLE
Moving all location API code inside a helper class

### ISSUE THREAD

**Issue by shubendra** [googlesamples/android-play-location#15]
In all samples the location API code is written inside a activity. wouldn't it be better if we move all logic inside a helper class. This way any activity can request the location by calling a function defined in helper class.

**Comment by shailen** [comment]
This is a eminently reasonable idea. The code is organized  the way it is to showcase very simple use cases for Location APIs. For a "real-world" app - even if it is very simple - the use of helper class or a library would indeed be the way to go. These samples are pedagogical in nature, hence the no-frills structuring of the code.
