### ISSUE TITLE
Can't load sample by following instructions

### ISSUE THREAD

**Issue by behelit** [googlesamples/android-play-location#154]
The following error is produced:

> Error:Cause: startup failed:
> settings file 'xxx\android-play-location-master\settings.gradle': 1: expecting EOF, found ',' @ line 1, column 205.
>    in:app' ':LocationUpdates:app', ':Locati
>                                  ^
> 
> 1 error

**Comment by jparmstr** [comment]
It's because there is a missing comma after the reference to the kotlin app in settings.gradle:

This: 
> ':LocationAddress:kotlin:app' ':LocationUpdates:app',

Should be:
> ':LocationAddress:kotlin:app', ':LocationUpdates:app',

**Comment by dturner** [comment]
Should be fixed now, please reopen if not.
