### ISSUE TITLE
Head Bang !...Cant use and run them in Eclipse ?

### ISSUE THREAD

**Issue by rahulfhp** [googlesamples/android-play-location#16]
Almost spent an hour trying fixes for the same. ?

Nothing in world seems to be working ? Can't I use them directly with import in eclipse? 

05-30 16:19:49.517: E/AndroidRuntime(12302): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.google.android.gms.location.sample.basiclocationsample/com.google.android.gms.location.sample.basiclocationsample.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.sample.basiclocationsample.MainActivity" on path: DexPathList[dexElements=[zip file "/data/app/com.google.android.gms.location.sample.basiclocationsample-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.google.android.gms.location.sample.basiclocationsample-1, /vendor/lib, /system/lib]]

**Comment by shailen** [comment]
Sorry, I am not an Eclipse expert, so I cannot offer direct help on this. The samples are written with Android Studio in mind. If your goal is to understand the use Play Services location APIs, perhaps you can open the samples using Android Studio?  

Can you ask about using the samples on StackOverflow?  There are probably a lot of Eclipse users out there who could help you. Sorry I cannot be of direct help.
