### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

### ISSUE THREAD

**Issue by alexd555** [googlesamples/android-play-location#177]
I got error:
No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

**Comment by RahulSDeshpande** [comment]
Hey @alexd555.

There are 2 solutions:
1) Update your Gradle version to the latest 
2) Rename the **/sdk/ndk-bundle** folder to some other name just to bypass the ndk sdk from the gradle build.

**Comment by dturner** [comment]
Thanks for reporting this. Should be fixed now, please re-open if not.
