### ISSUE TITLE
Running the App

### ISSUE THREAD

**Issue by weikengary** [googlesamples/android-play-location#18]
Hi,

Do i need to install this app onto 2 devices to test its functionality?

May i ask developers to provide screenshots of the app running and performing what it is supposed to?
thanks.

**Comment by Benweii** [comment]
Hello,
Test this app needs only  1 device, but you can run it on different devices for its stronger.
Point: 1.You can get location by gps or network ways, but each of them you need to open network first.
          2.If you run this app in china, you need to use vpn, which sure you can access google service.
          3.I'm not implements get location by google-play-service, so i modify source, add new activity, and implements get location by use LocationManager.

Following is screenshots of the app running and performing:

![3e283ecc8ee887e3-001](https://cloud.githubusercontent.com/assets/12572905/8073027/1cba004a-0f52-11e5-9e94-7606d4730aad.jpg)
![-6c6573b626e523b2](https://cloud.githubusercontent.com/assets/12572905/8073026/1cb91e82-0f52-11e5-820f-b7d3ef846a5e.jpg)

I wish it can help you.

**Comment by weikengary** [comment]
Hi thanks for reply.

I am refering to GeoFencing app sample.
Do i need 2 device to run this sample?

thanks.

**Comment by Benweii** [comment]
Sorry, i have not use GeoFencing, so i don't known about it.

**Comment by shailen** [comment]
No, you do not need two devices to run the Geofencing app. Any device with location services enabled should suffice. 

Also, please note that Google recommends using the Location services offered through Google Play Services over Android framework location APIs. See https://developer.android.com/training/location/index.html. I'm not aware of restrictions on the availability of Play Services in China, but all the location samples in this repo are designed to use Play Services, not android.location.

**Comment by shailen** [comment]
Closing this one. Please consider opening new issues if you notice problems with any of the samples. Also consider asking how-to questions on StackOverflow.
