### ISSUE TITLE
Geofencing samples link doesn't work...

### ISSUE THREAD

**Issue by geolyth** [googlesamples/android-play-location#2]
Hi, when I try to open this link https://github.com/googlesamples/android-play-location/tree/master/Geofences from readme, I receive 404 page error...

When I click on https://github.com/googlesamples/android-play-location/tree/master/Geofencing it works.

Dummy link, a simple wrong reference :-)

**Comment by shailen** [comment]
Thanks for catching this.

**Comment by shailen** [comment]
Fixed.
