### ISSUE TITLE
mGeofencePendingIntent never set

### ISSUE THREAD

**Issue by wernight** [googlesamples/android-play-location#20]
It seems that `mGeofencePendingIntent` is never set to anything except null (also in https://developer.android.com/training/location/geofencing.html).

**Comment by shailen** [comment]
Hmmm. How are you checking this? Also, what version of Google Play Services are you running? What build of Android? I ask because I'd like to be able to replicate what you see.

**Comment by wernight** [comment]
I'm just looking at the sample code on the given page and looked at the full source code in this repository.

**Comment by francisdb** [comment]
see https://github.com/googlesamples/android-play-location/blob/master/Geofencing/app/src/main/java/com/google/android/gms/location/sample/geofencing/MainActivity.java#L284
