### ISSUE TITLE
MainActivityTest failing

### ISSUE THREAD

**Issue by lwasyl** [googlesamples/android-play-location#21]
```
com.google.android.gms.location.sample.locationupdates.MainActivityTest > testUsingMockLocation[Nexus 4 - 5.1.1] FAILED
    junit.framework.AssertionFailedError: expected:<51.106829> but was:<90.0>
    at com.google.android.gms.location.sample.locationupdates.MainActivityTest.testUsingMockLocation(MainActivityTest.java:92)
:app:connectedAndroidTest FAILED
```

Actually it seems like I can't receive mock locations while using `FusedLocationProviderApi` at all. I pulled this repo to check what I'm doing wrong.

Btw it seems like `assertEquals` parameters in said test are in wrong order (first actual, then expected, should be the other way around).

**Comment by shailen** [comment]
The `assertEquals` params *were* in the wrong order. Thanks for pointing out. Now fixed. Also made a few changes to the test. Can you see if the test runs (and passes) for you? Also, can you tell me what version of Google Play Services you are using? And what build of Android? I'd like to be able to replicate what you found.

**Comment by lwasyl** [comment]
I just cloned the repo again, exactly the same error. The only steps I did were `git clone`, `gradle build` and `gradle connectedCheck`. *Allow mock locations* in developer options are selected.

I have HTC One M8 phone (Android 5.0.1, HTC Sense 6.0), Google Play Services 8.1.15 (2250156-238), although on older Play Services version the test was failing the same.

**Comment by lwasyl** [comment]
Hey,

I see that you have removed the test from the repo (https://github.com/googlesamples/android-play-location/commit/f01b254b87dc61a8dedca6e8a46b881d8ad7dac4) because it was `flaky`.

Yet still when I have to set mock location using new fused location provider client, after setting mock mode, adding my application as mock location app in developer setting, and setting mock location, nothing is received by the listener. Google Play Services 11.4.2. Do you have any idea whether the functionality is even supported, and how to use it? Otherwise I suppose you can close the issue, as it's no longer relevant, since the test is removed

**Comment by shailen** [comment]
As for "nothing is received by the listener", that could be because you have a static location after using the mock location, and there are no new updates to report.

**Comment by lwasyl** [comment]
> that could be because you have a static location after using the mock location, and there are no new updates to report

Shouldn't the new mock location be received, though? I understand that setting mock mode disables all other providers, but I don't get _any_ updates, including those I set as mock locations
