### ISSUE TITLE
Reasoning behind calling connect() / disconnect() on the googleApiClient in the onStart()/onStop() methods

### ISSUE THREAD

**Issue by appoll** [googlesamples/android-play-location#22]
Wouldn't it make more sense to have them called in the **onResume() / onPause()** methods? 
I would expect that if the user pauses the app to change the location settings (or any external event occurs), the change will be visible when he returns to the app.

**Comment by shailen** [comment]
No, the recommend pattern for GoogleApiClient is to call connect in onStart() and disconnect in onStop(), while using onResume() and onPause() to start and stop operations that need a connected GoogleApiClient (for instance, starting and stopping location updates).
