### ISSUE TITLE
GPS Bug on several older mobile devices

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [googlesamples/android-play-location#40]
I just tried the **BasicLocationSample** and it does not work on my Samsung GT-S7562 device. I went to a showroom and tested the same on several devices and it doesn’t work on Xiaomi redmi 2, Galaxy core prime as well. The sample works fine on newer models from these manufacturers. I even tested it on my OnePlus 2 and it works perfectly well.

There appears to be a bug that prevents GPS working on several devices and that needs to be addressed. I’ve been trying to find a solution so I figured trying out this Google Sample hoping that at least this would work coz it’s from the makers of Android but in vain. Basically it shows `No location detected. Make sure location is enabled on the device.` even with the **location enabled**.

Testing the **LocationUpdates** sample on the same devices gave NullPointException at updateUI() function regardless of whether Location is enabled or disabled. On the newer devices like the OP2, the NullPointerException appears only when Location is disabled and shows updates and works fine when Location is enabled.

**Comment by shailen** [comment]
Regarding this message:

"No location detected. Make sure location is enabled on the device"

Can you tell me the device make, the Android build, as well as the Google Play Services version?  I'd like to be able to recreate what you ran into and cannot do so without these data points. 

Also, would you mind posting the log data here? That'll help me diagnose the problems. Thanks.

**Comment by SaifurRahmanMohsin** [comment]
Here are the device details:

Device Make: Samsung Galaxy S Duos
Model: GT-S7562
Android version: 4.0.4 (IceCream Sandwich)
Baseband Version: S7562DDBNE1
Kernel version: 3.0.8-1279898
Android build: IMM761.S7562XXBNE2

**Comment by ajitdubey-mob-ibtech** [comment]
@shailen  is there any update regarding this issues because I am facing with same issue. Some devices working fine but not all devices.

**Comment by 786lokesh** [comment]
@SaifurRahmanMohsin and @ajitdubey-mob-ibtech That's because if you didn't have the cached location it will throws the NullPointerException. And make sure to add run time permissions as it is allowed for new versions of android.

**Comment by 786lokesh** [comment]
And you can also prompt to change the location settings.

**Comment by SaifurRahmanMohsin** [comment]
I’m certain those devices at the store run older versions of Android that do not use runtime permissions. Well I’m definitely sure with my Samsung GT-S7562 atleast. It’s running Android 4.0.3 so this looks more like one of the gazillion unsolved older bugs rather than one because of new android features.

**Comment by shailen** [comment]
The samples have all been updated recently.
