### ISSUE TITLE
GoogleApiClient not yet connected issue

### ISSUE THREAD

**Issue by hessmess** [googlesamples/android-play-location#49]
Hi,

When clicking the "request updates" button in the app, I always get the toast "GoogleApiClient not yet connected. TryAgain."
I cloned the repo and installed as is on a Galaxy Note running Marshmallow 5.0. Couldn't find a fix yet, any ideas?

**Comment by samtstern** [comment]
@hessmess the LocationUpdates sample has been updated, it no longer uses `GoogleApiClient` and should not have issues like this anymore.  Take a look!

**Comment by TdevM** [comment]
"Accessing Google APIs with GoogleApiClient (deprecated)"
[https://developers.google.com/android/guides/google-api-client](url)
Does that mean building GoogleApiClient to access FusedLocationProviderClient is no longer needed?
