### ISSUE TITLE
Null Last known location when using a coarse location permission

### ISSUE THREAD

**Issue by maboueita** [googlesamples/android-play-location#5]
In my case 
- target SDK: 21
- build tools version: 21.1.2
- play-services version: 6.5.87
- running the sample on a Lollipop physical device

I'm always getting a null last known location with ACCESS_COARSE_LOCATION permission in the manifest file. Only getting a valid object when using ACCESS_FINE_LOCATION.

**Comment by shailen** [comment]
Thanks for pointing this out. While I  cannot reproduce your experience, I would expect that one way something like this would happen is if the only location available was through GPS. I'll keep the issue open and test this out a bit more.

**Comment by shailen** [comment]
I am confirming that what you describe is an infrequent, but possible scenario where the last known location is simply null, even though I cannot reproduce what you've find on any device. Take a look at the isLocationAvailable() method and perhaps use that debug the state of location services on your device? Here's a link:  https://developers.google.com/android/reference/com/google/android/gms/location/LocationAvailability#isLocationAvailable()
