### ISSUE TITLE
Gradle, android gradle plugin and build tools are out-of-date.

### ISSUE THREAD

**Issue by zxx714** [googlesamples/android-play-location#56]
**The current version in project is**
- gradle 2.5
- buildTools 23.0.1
- android gradle plugin 1.3.1

**The latest version is** 
- gradle 2.14.1
- buildTools 24.0.2
- android gradle plugin 2.1.3

**Solution**
Update all of them to latest version.

**Comment by samtstern** [comment]
Closing this issue as we're now using recent versions (build tools 25.0.3, gradle plugin 2.3.2, etc)
