### ISSUE TITLE
Failed to crunch file

### ISSUE THREAD

**Issue by devtosystems** [googlesamples/android-play-location#57]
Hi there,
I have a problem with samplecode and google-play dependences and drawable icons.
Every time that I compile the project this error happens with icons:

```
Error: com.android.builder.internal.aapt.AaptException: Failed to crunch file 

C:\Users\Francis\Documents\projects\mobile\android-play-location\Geofencing\Application\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\8.4.0\res\drawable-mdpi\common_google_signin_btn_text_dark_normal.9.png into 

C:\Users\Francis\Documents\projects\mobile\android-play-location\Geofencing\Application\build\intermediates\res\merged\debug\drawable-mdpi\common_google_signin_btn_text_dark_normal.9.png
```

The icons exists but I not run my project because of that.
What's going wrong?

**Comment by Alexsan** [comment]
Try renaming the root folder into a shorter name: aplm/geofencing/application/...
Rebuild and run it again. See if that solves the problem.

**Comment by devtosystems** [comment]
Haha solved! :D
Thanks @Alexsan !

**Comment by artem-p** [comment]
Another solution that doesn't require to move the project is to change the build directory of the project in build.gradle:
`allprojects {
    buildDir = "C:/tmp/${rootProject.name}/${project.name}"
}` 

Taken from this [https://stackoverflow.com/questions/41267005/failed-to-crunch-file-android-studio-appmergedebugresources](url)
