### ISSUE TITLE
Why location must be enabled?

### ISSUE THREAD

**Issue by geolyth** [googlesamples/android-play-location#6]
Hi all,
I remember in previous google play services version was possible to instantiate a geofence without location enabled (only with Wi-Fi for example).

Why in this sample do not work?

I allready read "To run this sample, location must be enabled.", but in this way the battery becoming low in small time.

Thanks

**Comment by shailen** [comment]
Hi @geolyth . Sorry for the confusion: I just meant that *for this sample*, location must be enabled. It is not a statement about using geofences in general. Also, you might not that there is now a SettingsAPI associated with Location (I've just added a LocationSettings sample to this repo that shows how it works), and for any location work, the SettingsApi can be used to determine what is required and what isn't (and upgrade if necessary).
