### ISSUE TITLE
Request location updates from Service

### ISSUE THREAD

**Issue by lawloretienne** [googlesamples/android-play-location#7]
All of the samples show location updates being requested from an activity.  Can this logic be moved to a IntentService, that way in the background you can monitor a user's location.

Specifically I want to use this so that I can dynamically remove and then add geofences as a users location significantly (the user moves more than 20 miles) changes.

**Comment by shailen** [comment]
I think this is an excellent idea. The samples currently in this repo are of 101 variety, providing the simplest use cases for an API. But you are right, a more realistic use case would involve moving a lot of the work to the background. I'll add another sample showing how to do monitor geofences in the background and dynamically add/remove geofences. Thanks for the input.

**Comment by farmazon3000** [comment]
Any news on this issue?
