### ISSUE TITLE
Samples for Drive connectionless API

### ISSUE THREAD

**Issue by NLLAPPS** [googlesamples/android-play-location#78]
I know it is not a right place but I can;t seem to find any Drive Api samples with new connectionless API
Is it available?

**Comment by samtstern** [comment]
@NLLAPPS Location Services is the first `GoogleApiClient` API to convert to the new connectionless style but we are working on the rest!  Look out for changes in future releases to Drive and other APIs.  I can't share a timeline right now.

**Comment by NLLAPPS** [comment]
Thanks! I can't wait
