### ISSUE TITLE
Cannot run MainActivityTest

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-play-location#8]
I get an error:
> FAILURE: Build failed with an exception.
* What went wrong:
Task 'cleanTest' not found in project ':app'.
* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 1.607 secs
Task 'cleanTest' not found in project ':app'.

**Comment by shailen** [comment]
I assume this is with LocationUpdates?  How are you running the test? Are you using Android Studio? Ca you give some more details?

**Comment by IgorGanapolsky** [comment]
Yup, using Android Studio.  Just right click on the test class and run it!

**Comment by shailen** [comment]
I reproduced the problem. I'll try to fix this soonish. PRs are also welcome :)

**Comment by shailen** [comment]
I've updated the code. Can you try it now?

**Comment by IgorGanapolsky** [comment]
Hello,
I just tried to run the test, and got this error:
> In order to use mock mode functionality app com.google.android.gms.location.sample.locationupdates must have the ACCESS_MOCK_LOCATION permission and the Settings.Secure.ALLOW_MOCK_LOCATION system setting must be enabled.

Perhaps you should put that in the **debug/Androidmanifest.xml** file?

**Comment by shailen** [comment]
I believe this works now. Please create a new issue if the problem persists.
