### ISSUE TITLE
Geofence Testing

### ISSUE THREAD

**Issue by lawloretienne** [googlesamples/android-play-location#9]
What is the best way to test Geofencing?  I wrote a blog article on this subject matter

http://lawloretienne.github.io/blog/

but now am having issues with the Google Maps app on the Genymotion device.  Aside from physically going in and out of Geofences, what are the alternatives?

Also, I have set up geofences for stores inside a mall but don't see them triggering a notification.  Do geofences still work inside of a mall?

**Comment by shailen** [comment]
Try using setMockMode() and setMockLocation() to mock out a location. Details at https://developer.android.com/reference/com/google/android/gms/location/FusedLocationProviderApi.html#setMockLocation(com.google.android.gms.common.api.GoogleApiClient, android.location.Location).

As for your second question: geofences should work inside a mall, but the recommended area is ~150 ft, so perhaps that is affecting your use case. 

Thanks for asking. Closing this issue. Can you ask these questions on StackOverflow? That way, a wider  group of developers can follow the discussion.
