### ISSUE TITLE
Cannot resolve symbol 'main_activity_container'

### ISSUE THREAD

**Issue by JohnnyDevv** [googlesamples/android-play-location#95]
The error is on line 129 of the MainActivity.java file. That is the only error I am facing at the moment. please what do I do? Thanks!

**Comment by samtstern** [comment]
Looks like you're talking about this line:
https://github.com/googlesamples/android-play-location/blob/87f5c3951d6a40cc63a639e71656019246ed51b0/BasicLocationSample/app/src/main/java/com/google/android/gms/location/sample/basiclocationsample/MainActivity.java#L129

But the ID is defined here:
https://github.com/googlesamples/android-play-location/blob/d8ac490263ec295e9886208377752472a2cce4d8/BasicLocationSample/app/src/main/res/layout/main_activity.xml#L18

So it's likely the problem has to do with your development environment.  Verify that you can build from the command line with `./gradlew`

**Comment by JohnnyDevv** [comment]
Oh! I forgot to define the ID in the layout, thanks!
