### ISSUE TITLE
Question: is it possible to get location indoors, without GPS signal?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-play-location#96]
Suppose you are indoors, or inside a parking lot that's underground. 

Is it possible to get location in this situation, that GPS is not available?

Is it possible to even navigate to such a location ?

**Comment by shailen** [comment]
Yes, FusedLocationProvider APIs work with GPS, Wifi, Cell, and several sensor inputs to compute location. In the scenario you describe, some combination of Wifi, Cell, and sensors will be used for location.

**Comment by AndroidDeveloperLB** [comment]
So it will be able to know where I am even in an underground parking lot?
